package ar.edu.itba.dreamtrip.common.API.dependencies;

/**
 * Created by Julian Benitez on 11/15/2016.
 */

public enum DependencyType {
    AIRLINES, COUNTRIES, CITIES, AIRPORTS, CURRENCIES, FLIGHTS, IMAGE, AIRLINES_LOGOS,
    AIRLINES_DATA, FLIGHT_SEARCH, TRACKED_FLIGHTS, FLIGHT_STATUS, AIRLINE_REVIEWS,
     LAST_MINUTE_DEALS_IMAGES, LAST_MINUTE_DEALS_DATA, LAST_MINUTE_DEALS, LAST_MINUTE_DEALS_IMAGES_URLS
}
