package ar.edu.itba.dreamtrip.common.API.dependencies;

public enum DependencyType {
    AIRLINES, COUNTRIES, CITIES, AIRPORTS, CURRENCIES, FLIGHTS, IMAGE, AIRLINES_LOGOS,
    AIRLINES_DATA, FLIGHT_SEARCH, TRACKED_FLIGHTS, FLIGHT_STATUS, AIRLINE_REVIEWS,
     LAST_MINUTE_DEALS_IMAGES, LAST_MINUTE_DEALS_DATA, LAST_MINUTE_DEALS, LAST_MINUTE_DEALS_IMAGES_URLS,
     DEALS_IMAGES, DEALS_DATA, DEALS, DEALS_IMAGES_URLS
}
